=== Al12rs/TecWeb/Esame2017-09-15/Es2ParserDOMBibliotecaMusicaleVarianteAttributi/resources/bibliotecaMusicale.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Tipo brano -->
    <xs:complexType name="branoType">
        <xs:sequence>
            <xs:element name="titoloBrano" type="xs:string" />
            <xs:element name="lunghezzaBrano">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]*:[0-5][0-9]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Tipo lista brani -->
    <xs:complexType name="listaBraniType">
        <xs:sequence>
            <xs:element name="brano" type="branoType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Tipo album -->
    <xs:complexType name="albumType">
        <xs:sequence>
            <xs:element name="titoloAlbum" type="xs:string"/>
            <xs:element name="annoPubblicazione" type="xs:positiveInteger"/>
            <xs:element name="listaBrani" type="listaBraniType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Tipo musicista -->
    <xs:complexType name="musicistaType">
        <xs:sequence>
            <xs:element name="album" type="albumType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="nome" type="xs:string" use="required"/>
        <xs:attribute name="cognome" type="xs:string" use="required"/>
        <xs:attribute name="nomeArte" type="xs:string" use="optional"/>
        <xs:attribute name="genereMusicale" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Elemento definito-->
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="musicista" type="musicistaType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Al12rs/TecWeb/Esame2017-09-15/Es2ParserDOMBibliotecaMusicaleVarianteAttributi/resources/bibliotecaMusicale1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibliotecaMusicale.xsd"><musicista cognome="Verdi" genereMusicale="Opera" nome="Giuseppe"><album><titoloAlbum>Aida</titoloAlbum><annoPubblicazione>1840</annoPubblicazione></album></musicista><musicista cognome="Pallino" genereMusicale="Rap" nome="Pinco" nomeArte="ElPanco"><album><titoloAlbum>In the ghetto</titoloAlbum><annoPubblicazione>2013</annoPubblicazione><listaBrani><brano><titoloBrano>Homies forever</titoloBrano><lunghezzaBrano>4:23</lunghezzaBrano></brano></listaBrani></album><album><titoloAlbum>Brotherhood</titoloAlbum><annoPubblicazione>2015</annoPubblicazione><listaBrani><brano><titoloBrano>Run for your lives</titoloBrano><lunghezzaBrano>2:12</lunghezzaBrano></brano><brano><titoloBrano>Survivors</titoloBrano><lunghezzaBrano>3:15</lunghezzaBrano></brano></listaBrani></album><album><titoloAlbum>RapDeity</titoloAlbum><annoPubblicazione>2017</annoPubblicazione></album></musicista></biblioteca>
